# -*- coding: utf-8 -*-
"""turtle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kXYOvKiw9Czk-hiGKEbCQKCowwnh63Oy

First you have to install ColabTurtle
"""

!pip3 install ColabTurtle

"""Import ColabTurtle.Turtle"""

from ColabTurtle.Turtle import *

"""Then you need to intilise a turtle"""

initializeTurtle()

"""Do what ever you want!"""

speed(10)
color('cyan')
bgcolor('black')

b = 400
while b>0:
  left(b)
  forward(b*3)
  b = b-1

speed(10)
color('cyan')
bgcolor('black')

b = 200
while b>0:
  left(b)
  forward(b*3)
  b = b-1